// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechEval.Infrastructure.Persistence;

#nullable disable

namespace TechEval.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TechEvalDbContext))]
    [Migration("20260320150000_Fase8_EvaluacionDinamica")]
    partial class Fase8_EvaluacionDinamica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TechEval.Domain.Evaluaciones.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("TechEval.Domain.Evaluaciones.Evaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CantidadPreguntasSesion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ModoSeleccionPreguntas")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("OrdenAleatorio")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrdenPorDificultad")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("evaluaciones", (string)null);
                });

            modelBuilder.Entity("TechEval.Domain.Evaluaciones.OpcionRespuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsRevisionManual")
                        .HasColumnType("boolean");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Puntuacion")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("opciones_respuesta", (string)null);
                });

            modelBuilder.Entity("TechEval.Domain.Evaluaciones.Pregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsRevisionManual")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LimiteTiempoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("NivelDificultad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<bool>("PermiteAdjunto")
                        .HasColumnType("boolean");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TipoPregunta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("categoria_id")
                        .HasColumnName("categoria_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("categoria_id");

                    b.ToTable("preguntas", (string)null);
                });

            modelBuilder.Entity("TechEval.Domain.Resultados.PuntuacionPregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("FueExpirada")
                        .HasColumnType("boolean")
                        .HasColumnName("fue_expirada");

                    b.Property<string>("JustificacionIA")
                        .HasColumnType("text")
                        .HasColumnName("justificacion_ia");

                    b.Property<int>("NumeroPregunta")
                        .HasColumnType("integer")
                        .HasColumnName("numero_pregunta");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PreguntaSesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pregunta_sesion_id");

                    b.Property<decimal?>("PuntuacionAutomatica")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("puntuacion_automatica");

                    b.Property<decimal?>("PuntuacionIASugerida")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("puntuacion_ia_sugerida");

                    b.Property<decimal?>("PuntuacionManual")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("puntuacion_manual");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("respuesta");

                    b.Property<Guid>("ResultadoEvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TiempoEmpleadoSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_empleado_segundos");

                    b.Property<string>("TipoPregunta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_pregunta");

                    b.Property<string>("UrlAdjunto")
                        .HasColumnType("text")
                        .HasColumnName("url_adjunto");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaSesionId");

                    b.HasIndex("ResultadoEvaluacionId");

                    b.ToTable("puntuaciones_pregunta", (string)null);
                });

            modelBuilder.Entity("TechEval.Domain.Resultados.TranscripcionEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Contenido")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("JustificacionIA")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<decimal?>("PuntajeIA")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ResultadoEvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("UrlArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoEvaluacionId");

                    b.HasIndex("Tipo");

                    b.ToTable("transcripciones_evaluacion", (string)null);
                });


            modelBuilder.Entity("TechEval.Domain.Resultados.ResultadoEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CandidatoId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("candidato_id");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("integer")
                        .HasColumnName("estado_revision");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluacion_id");

                    b.Property<string>("EvaluadorRevision")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("evaluador_revision");

                    b.Property<DateTime>("FechaCompletacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_completacion");

                    b.Property<DateTime?>("FechaFinRevision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_revision");

                    b.Property<DateTime?>("FechaInicioRevision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_revision");

                    b.Property<string>("NombreCandidato")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre_candidato");

                    b.Property<decimal>("PorcentajeObtenido")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_obtenido");

                    b.Property<decimal>("PuntuacionMaxima")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("puntuacion_maxima");

                    b.Property<decimal>("PuntuacionTotal")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("puntuacion_total");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<int>("TiempoTotalSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_total_segundos");

                    b.Property<string>("TituloEvaluacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("titulo_evaluacion");

                    b.Property<int>("ViolacionesPestana")
                        .HasColumnType("integer")
                        .HasColumnName("violaciones_pestana");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EstadoRevision");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("SesionId")
                        .IsUnique();

                    b.ToTable("resultados_evaluacion", (string)null);
                });

            modelBuilder.Entity("TechEval.Domain.Sesiones.PreguntaSesion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FueRespondida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("LimiteTiempoSegundos")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RespuestaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SesionEvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("TiempoExpirado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("RespuestaId");

                    b.HasIndex("SesionEvaluacionId");

                    b.ToTable("preguntas_sesion", (string)null);
                });

            modelBuilder.Entity("TechEval.Domain.Sesiones.RespuestaCandidato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BrindadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FueExpiratoElTiempo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("TiempoEmpleadoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("UrlAdjunto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("respuestas_candidato", (string)null);
                });

            modelBuilder.Entity("TechEval.Domain.Sesiones.SesionEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CandidatoId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("CompletadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContadorViolacionesPestana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("IniciadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxViolacionesPestana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("UrlGrabacionAudio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UrlGrabacionSesion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("CodigoAcceso")
                        .IsUnique();

                    b.HasIndex("EvaluacionId");

                    b.ToTable("sesiones_evaluacion", (string)null);
                });

            modelBuilder.Entity("TechEval.Infrastructure.Identity.RefreshTokenEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revocado")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TechEval.Infrastructure.Identity.UsuarioApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechEval.Infrastructure.Identity.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechEval.Infrastructure.Identity.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechEval.Infrastructure.Identity.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechEval.Infrastructure.Identity.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechEval.Domain.Evaluaciones.OpcionRespuesta", b =>
                {
                    b.HasOne("TechEval.Domain.Evaluaciones.Pregunta", null)
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechEval.Domain.Evaluaciones.Pregunta", b =>
                {
                    b.HasOne("TechEval.Domain.Evaluaciones.Evaluacion", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechEval.Domain.Resultados.PuntuacionPregunta", b =>
                {
                    b.HasOne("TechEval.Domain.Resultados.ResultadoEvaluacion", null)
                        .WithMany("Puntuaciones")
                        .HasForeignKey("ResultadoEvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechEval.Domain.Resultados.TranscripcionEvaluacion", b =>
                {
                    b.HasOne("TechEval.Domain.Resultados.ResultadoEvaluacion", null)
                        .WithMany("Transcripciones")
                        .HasForeignKey("ResultadoEvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });


            modelBuilder.Entity("TechEval.Domain.Sesiones.PreguntaSesion", b =>
                {
                    b.HasOne("TechEval.Domain.Sesiones.RespuestaCandidato", "Respuesta")
                        .WithMany()
                        .HasForeignKey("RespuestaId");

                    b.HasOne("TechEval.Domain.Sesiones.SesionEvaluacion", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("SesionEvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("TechEval.Domain.Evaluaciones.Evaluacion", b =>
                {
                    b.Navigation("Preguntas");

                    b.OwnsOne("TechEval.Domain.Evaluaciones.DistribucionDificultad", "DistribucionDificultad", b1 =>
                        {
                            b1.Property<Guid>("EvaluacionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Dificil")
                                .HasColumnType("integer")
                                .HasColumnName("distribucion_dificil");

                            b1.Property<int>("Facil")
                                .HasColumnType("integer")
                                .HasColumnName("distribucion_facil");

                            b1.Property<int>("Medio")
                                .HasColumnType("integer")
                                .HasColumnName("distribucion_medio");

                            b1.HasKey("EvaluacionId");

                            b1.ToTable("evaluaciones");

                            b1.WithOwner()
                                .HasForeignKey("EvaluacionId");
                        });
                });

            modelBuilder.Entity("TechEval.Domain.Evaluaciones.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("TechEval.Domain.Resultados.ResultadoEvaluacion", b =>
                {
                    b.Navigation("Puntuaciones");

                    b.Navigation("Transcripciones");
                });

            modelBuilder.Entity("TechEval.Domain.Sesiones.SesionEvaluacion", b =>
                {
                    b.Navigation("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
